### ISSUE TITLE
Clarify various licenses used by GBDK-2020

### ISSUE THREAD

**Issue by asiekierka** [gbdk-2020/gbdk-2020#388] opened 2022-07-03 21:41 UTC
The root of the repository contains an MIT LICENSE file, with no clarifications as to any other copyright responsibilities that may fall on the end user. However, we know that some components are under other licenses, for example:

* the SDCC runtime library inclusions are under GPLv2+ w/ binary linking exception,
* bankpack is under a public domain-style dedication,
* etc.

There are probably more. So, the LICENSE file is not clear as to the end user's copyright responsibilities... However, a more pressing question is this - when @Zal0 [imported the source code of GBDK 2.96a](https://github.com/gbdk-2020/gbdk-2020/commit/11a44c3cad913f0bacf77257199fa0bc0c10541b), did they acquire any relicensing permission from **all** of GBDK's original contributors?

GBDK's original license is *not* MIT at all. Citing from the original website:

>GBDK is freeware for non-commercial developments. Most of the code is under the GPL. The runtime libraries should be under the LGPL. The non-commercial clause is from the C front end, lcc. If you use it, please send me an e-mail to keep me informed of your work. If you really find it great, you can send me something typical from your country... 
>
>If GBDK is used for developing a commercial program, I ask you to mention that the program has been made using GBDK (in the credits), and to send me a copy of the finished product. If you feel generous, you can also send me a copy of any other products that your company has produced for the GameBoy...

The license, as implied, is quite contradictory - "most of the code is under the GPL", "the runtime libraries should be under the LGPL", "non-commercial clause [...] lcc", "commercial program [...] send me a copy of the finished product". This should be rather concerning, as many GBDK-using software has already been released commercially. (Naturally, the lcc part of the text should no longer apply, as lcc is no longer used - but GPL/LGPL statements are worrisome, as they do not automatically include an SDCC-style binary linking exception.)

One could assume that Michael Hope is at least aware of gbdk-2020, given the SourceForge page.

Could the LICENSE file be updated to (a) clarify *all* licenses that apply to the combined toolchain, and ideally (b) document evidence of contributors who created the work prior to gbdk-2020's MIT license having agreed to some FOSS licensing terms? (
Pascal Felber, Lars Malmborg, Michael Hope are listed in the README, [drawing.s](https://github.com/gbdk-2020/gbdk-2020/blob/develop/gbdk-lib/libc/targets/sm83/drawing.s) names Jon Fuge, no other contributors seem to be in the CVS history but that may also be incomplete)

**Comment by bbbbbr** [comment] 2022-07-04 00:54
Agreed that there could be more organized documentation about which parts of GBDK are under which licenses.

Nothing has been re-licensed though. The MIT license seems to be a catch-all for whatever remains after specific licenses apply. This can be clarified.

* No longer applicable:
  * The LCC compiler: (the non-commercial restriction - which is in regard to products whose value is based _on the compiler itself or significant parts of it_, not the compiled output) has been replaced with SDCC (change made pre-GBDK-2020)
  * The maccer / aslink / etc: no longer included or used

* Currently:
  * `GBDK Library`: SDCC GPL with linking exception, or LGPL (based on quoted gbdk site text). The licensing for this has not changed. See below for comments about LGPL + original GBDK libraries.
  * `makebin`: SDCC GPL. It's inclusion is a recent, and hopefully temporary fork pending changes merged upstream in SDCC
  * `bankpack, ihxcheck, gbcompress, makecom` : I'm the author of these, they are in the public domain and indicated as such
  * `png2asset`: @Zal0 is the original author + additional contributors, probably inherits the repo's general MIT license but he can indicate differently if this is not the case
  * The `Makefiles`: I guess are GPL, but that doesn't seem like a pressing matter
  * The `LCC front end / compiler driver`: This seems to be a lingering fragment extracted from the LCC compiler project. But based on reading the original license (which may have been removed when GBDK switched to SDCC) as described above it doesn't appear to have a problem. But should probably have it's own separate license file from the original project.


Yes, Michael Hope (@nzmichaelh) is aware of GBDK-2020. We briefly exchanged some email in 2020. 
  * We can see if he'd like to formally waive the ask below (I wonder how many have actually performed that over the last 20 years, and perhaps he may not want hundreds of people using GBDK + ZGB + GBStudio contacting him).
  * And perhaps also clarify the LGPL status of the original library code
> ("If GBDK is used for developing a commercial program, I ask you to mention that the program has been made using GBDK (in the credits), and to send me a copy of the finished product. If you feel generous, you can also send me a copy of any other products that your company has produced for the GameBoy... "

In conclusion:
- [ ] Add LICENSE file for `makecom`
- [ ] Add LICENSE file for `makebin`
- [ ] Add original CPYRIGHT file for lcc
- [ ] Confirm `png2asset` license is MIT (or whatever)
- [ ] Update main repo LICENSE to generally outline what is described above
- [ ] Clarify LGPL with regard to original `GBDK libraries`
   - Since it's unlikely anyone has (or will) distribute Game Boy ROMs which dynamically link the library code they use, it's possible that the original GBDK authors may have selected the LGPL license with some intent of a static linking exception. Otherwise it doesn't make much sense to select the LGPL unless they indented people to distribute ROMs in object format and have people link the ROMs themselves before using them as an alternative.
- [ ] Potentially clarify the ask for copies of finished products based on GBDK
 

Also see:
https://github.com/gbdk-2020/gbdk-2020/issues/55
https://github.com/gbdk-2020/gbdk-2020/issues/114

**Comment by asiekierka** [comment] 2022-07-04 05:53
The GBDK library code still includes work by other people (Jon Fuge is explicitly credited in one source file, Pascal Felber and Lars Malmborg may also have had contributions), and I am not sure if Michael has copyright assignments for them, so this might be a bit trickier.

I've done a brief check, and the following people are credited in source files (most source files lack credit, however):

* Jon Fuge - `drawing.s`
* ISSOtm - `crash_handler.s` (under [this license](https://github.com/ISSOtm/gb-starter-kit/blob/master/LICENSE))
* Michael Hope - `font.s` etc. - Artistic License 

`far_ptr.s` and `heap.s` additionally are derived from SDCC, so they're under GPLv2+ with the SDCC linking exception.

The Makefiles are not a pressing matter, I agree. The most pressing matter is the code that gets statically linked to create a final ROM, as those copyright requirements extend directly to GBDK users and distributors.

**Comment by bbbbbr** [comment] 2022-07-04 06:03
I've reached out to Michael with some of the questions raised.

**Comment by nzmichaelh** [comment] 2022-07-05 18:37
Hi folks. I don't recognise that text, but it looks like it comes from before my time. I agree that GBDK should be usable for any type of project, commercial or otherwise, and am happy to relicense anything I have the copyright to under something like the MIT license or BSD 2 clause.

Let me know,

**Comment by untoxa** [comment] 2022-07-05 19:35
Oh, Thank You, Michael! May we simply remove the license info from those files or replace it with the MIT text? We'll keep your name there. I don't put any license info the each of my own files for instance.

**Comment by bbbbbr** [comment] 2022-07-05 20:42
Same, thank you for helping to straighten this out.
 
Since some parts of the GBDK library from SDCC are under an LGPL + Linking Exception license, it might be most practical to just add the Linking Exception to the remaining parts of the GBDK library from the original GBDK  (so they become LGPL + LE instead of LGPL). That way there is a single license type which covers all of it.

For the rest that isn't covered by other licenses (Makefiles + bits of Docs integrated into the new docs) , MIT is probably fine. 

The text @asiekierka quoted is from the "Status" paragraph near the bottom of the original GBDK sourceforge website.
http://gbdk.sourceforge.net/

**Comment by asiekierka** [comment] 2022-07-07 15:15
> Some of the routines in the core+support libraries are also derived from disassembled code that you find in pretty much every GB game (I can probably dig that out in my archives from early GBDK releases).

*Uh oh.*

**Comment by bbbbbr** [comment] 2022-07-07 18:29
> I've been told by two independent sources that other files in GBDK may also contain code that 
> is suspiciously similar to official Nintendo code (and distinct from non-GBDK homebrew).
> In particular, pad.s has been named as such a culprit.
> I would highly recommend arranging an audit, if at all possible.

Hi, please refrain from speculation.

If you have specific examples of code compared with reference code then you are welcome to share those and we can look at them, but otherwise please stick to concrete information. More generally, I would also ask that you not use anonymous sources as part of the discussion in this ticket.

**Comment by untoxa** [comment] 2022-07-07 18:29
pad.s is a suggested code from the documentation. you can't say in the documentation "do like this: ..." and then take everybody to trial for that.

**Comment by asiekierka** [comment] 2022-07-07 18:34
> you can't say in the documentation "do like this: ..." and then take everybody to trial for that.

You can, if the code is not meant to be used by homebrew developers. Example code in a documentation is still copyrighted by *someone*.

I cannot provide specific examples, as doing so would be equivalent to me having knowledge of official Nintendo code, which I do not. I also am not going to name people who send me concerned DMs in public without their permission - they can post here, if they so wish.

**Comment by bbbbbr** [comment] 2022-07-07 19:17
**I want to keep this discussion focused and on track, so advance notice:** I am going remove comments from the thread related to speculation and vague statements about theoretical issues. They have the potential to derail the discussion are not a good use of people's time and energy.

* If there are specific examples of code compared with reference code then they can be reviewed.
* Do not use anonymous sources and material which cannot be shared for review as part of the discussion in this ticket.

**Comment by ISSOtm** [comment] 2022-07-07 19:43
The example I was asked to verify was `_joypad`, which uses the exact same input polling method as the snippet in page 24 of the "Game Boy programming manual", version 1.0.

https://github.com/gbdk-2020/gbdk-2020/blob/a92b1d4c991e4b475a5d3404cfc2a0b8227af0b4/gbdk-lib/libc/targets/sm83/pad.s#L30-L53

I asked for my name not to be shared *publicly* because then it would constitute public admittance of looking at official Nintendo code, and I would've rather avoided that. This matter could have been continued civilly in private—both of you are currently able to contact asie privately.

I personally dislike that, despite asie acting in good faith and warning you of copyright infringement issues that affect past and future users, you defaulted to treating his claims as "speculation" because he tried to protect his sources and himself, and you are asking *others* do do *your* due diligence. I can't fault asie for throwing the sponge, given the inadequacy of the responses above to this serious problem.

**Comment by untoxa** [comment] 2022-07-07 20:17
i am quite sure that the code is completely different from what you have read on that page 24.

**Comment by bbbbbr** [comment] 2022-07-07 21:07
We have finite time and other things to work on, so yes we do ask that people only raise issues once they have confirmed information which they can share with us. People are, of course, also welcome to reach out to us privately if they are not comfortable doing so in public.

**Comment by untoxa** [comment] 2022-07-08 11:52
1. reading of the nintendo doc by itself is not illegal. it is illegal to distribute it in whole or by parts. and, as i guess, only for those, who signed an NDA with nintendo, but that is a very unconnected subject, let's not discuss that here.
2. that code snippet on "page 24" - is a function for returning of the value of 0x30 in A. GBDK-2020 joypad() function does the very different thing
3. GBDK-2020 code does not even have two matching instructions in a row with the discussed snippet, which should be obvious to one who positions himself as experienced sm83 assembly developer
i think we may close the pointless discussion of pad.s internals now

**Comment by bbbbbr** [comment] 2022-07-18 07:58
Removed only code attributed to Lars Malmborg & Jeff Frohwein (GB wav playback sample).

**Comment by bbbbbr** [comment] 2022-07-28 06:06
## Relicensing of GBDK Library & Makefiles

As mentioned [above](https://github.com/gbdk-2020/gbdk-2020/issues/388#issuecomment-1175479509), the way forward is to re-license the library code to GPLV2 + LE to match the parts from SDCC so that all library code uses the same license.

To that end:

1. This is from Jon Fuge @jf1452 when asked about re-licensing his contributions to GPL or GPLv2 with a Linking Exception (to have the same licenses as the SDCC library code):

    > Yes, completely happy to re-license the code to make it more accessible and link to my GitHub account.

     (queued commit #389 has updated attribution to github account)


2. Earlier in this issues @nzmichaelh mentioned being ok with re-licensing to MIT or BSD2. 

    However instead of MIT or BSD2, I'd like to get a final formal consent from both @nzmichaelh and @pfelber for GPLv2 + LE (linking exception) if that is acceptable.

3. I've staged a PR that can be merged if & when the re-licensing finalized. #389

**Comment by nzmichaelh** [comment] 2022-08-04 08:44
GPLv2 + LE SGTM, go for it.

**Comment by bbbbbr** [comment] 2022-08-04 18:11
Great! 

We've got the required signoff so I'll start the repo changes and we're good to go.

Thank you so much Michael, Pascal and Jon for allowing the re-license. We really appreciate the time you've taken to help resolve this issue and clear up any license ambiguity.

**Closed by bbbbbr** 2022-08-04 18:11 UTC
